### ISSUE TITLE
快捷键能否支持两段快捷键（双击Ctrl等等）

### ISSUE THREAD

**Issue by vagra** [pot-app/pot-app-plugin-list#16]
我以前使用 QTranslate ，这个翻译软件非常好，界面是一般，但是呢，它支持快捷键的自由配置，特别是支持两段式的快捷键，比方说，选中文字后，双击 Ctrl 就可以翻译。

两段式快捷键有什么好处呢？好处就是说，因为许多常用软件的快捷键都是一段式的组合快捷键，Ctrl+C，Ctrl+V，Ctrl+Z之类的，那么，如果我们在翻译软件中也使用一段式快捷键，那么，我们基本不可能找到一个快捷键组合，让它在各个常用软件中都不冲突。

相反的如果使用两段式快捷键，比方说双击Ctrl，那么冲突的可能性就非常少了。

事实上现在一些便捷工具比方说，Listray, Flow launcher，都支持两段式快捷键。

**Comment by Pylogmon** [comment]
为什么要在这个仓库提issue？
