### ISSUE TITLE
语音不能播放该怎么办啊？

### ISSUE THREAD

**Issue by yhrss** [pot-app/pot-app-plugin-list#18]
{
"code": "InvalidRequest",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial",
"innerError": {
"code": "InvalidPayload",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial"
}
}
 One is always 0 n a strange road watching strange scenery and listening tO strange music. Then one day, you will find that the things you try hard to forget are already gone.
英语
{
"code": "InvalidRequest",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial",
"innerError": {
"code": "InvalidPayload",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial"
}
}
人はいつも見知らぬ道で、見知らぬ景色を眺め、見知らぬ音楽を聴いている。そしてある日、忘れようと懸命になっているものがすでになくなっていることに気づく。
{
"code": "InvalidRequest",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial",
"innerError": {
"code": "InvalidPayload",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial"
}
}
見知らぬ景色を眺めたり、見知らぬ音楽を聴いたりしながら、いつも見知らぬ道を歩いている。そしてある日、一生懸命忘れようとしていたものがすでになくなっていることに気づくでしょう。
{
"code": "InvalidRequest",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial",
"innerError": {
"code": "InvalidPayload",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial"
}
}
一つは、常に0n奇妙な道奇妙な風景を見て、奇妙な音楽を聴いています。 そして、ある日、あなたはあなたが忘れて懸命にしようとするものはすでになくなっていることがわかります。
{
"code": "InvalidRequest",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial",
"innerError": {
"code": "InvalidPayload",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial"
}
}
人はいつも、見知らぬ道を通って、奇妙な景色を眺め、奇妙な音楽を聴いている。そしてある日、一生懸命忘れようとしていたものがすでになくなっていることに気づくでしょう。
{
"code": "InvalidRequest",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial",
"innerError": {
"code": "InvalidPayload",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial"
}
}

{
"code": "InvalidRequest",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial",
"innerError": {
"code": "InvalidPayload",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial"
}
}
One is always 0 n a strange road watching strange scenery and listening tO strange music. Then one day, you will find that the things you try hard to forget are already gone.
{
"code": "InvalidRequest",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial",
"innerError": {
"code": "InvalidPayload",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial"
}
}
不思議な道で不思議な景色を見たり、不思議な音楽を聴いたりしていると、いつか忘れようと努力していたものがもうなくなっていることに気づくでしょう。
{
"code": "InvalidRequest",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial",
"innerError": {
"code": "InvalidPayload",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial"
}
}
1つは、常に0 n奇妙な道奇妙な景色を見て、奇妙な音楽を聞いています。そしてある日、一生懸命忘れていたものがもうなくなっていることに気付く。

**Comment by Pylogmon** [comment]
这个插件已经凉了，换其他的吧
